import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import SyncUser from "@/components/SyncUser";

export const metadata: Metadata = {
  title: "SeoulCourse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="ko">
        <body className={` antialiased `}>
          <SignedIn>
            <SyncUser />
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
