import { Camera, Coffee, ShoppingBag } from "lucide-react";

export const guData = [
  {
    id: "11680",
    name: "강남구",
    color: "#FF6B6B",
    hotspot: "청담·압구정",
    vibe: "럭셔리",
    rating: 4.7,
    visitors: "2.8K",
  },
  {
    id: "11740",
    name: "강동구",
    color: "#4ECDC4",
    hotspot: "천호동",
    vibe: "활기찬",
    rating: 4.3,
    visitors: "1.4K",
  },
  {
    id: "11305",
    name: "강북구",
    color: "#95E1D3",
    hotspot: "수유리먹자골목",
    vibe: "로컬",
    rating: 4.2,
    visitors: "1.1K",
  },
  {
    id: "11500",
    name: "강서구",
    color: "#FFE66D",
    hotspot: "마곡",
    vibe: "신도시",
    rating: 4.3,
    visitors: "1.6K",
  },
  {
    id: "11620",
    name: "관악구",
    color: "#A8E6CF",
    hotspot: "신림동",
    vibe: "대학가",
    rating: 4.1,
    visitors: "1.3K",
  },
  {
    id: "11215",
    name: "광진구",
    color: "#FFB347",
    hotspot: "건대입구",
    vibe: "젊음",
    rating: 4.5,
    visitors: "2.2K",
  },
  {
    id: "11530",
    name: "구로구",
    color: "#DDA15E",
    hotspot: "구로디지털단지",
    vibe: "비즈니스",
    rating: 4.0,
    visitors: "1.2K",
  },
  {
    id: "11545",
    name: "금천구",
    color: "#BC6C25",
    hotspot: "가산디지털단지",
    vibe: "테크",
    rating: 3.9,
    visitors: "1.1K",
  },
  {
    id: "11350",
    name: "노원구",
    color: "#606C38",
    hotspot: "상계동",
    vibe: "주거",
    rating: 4.2,
    visitors: "1.5K",
  },
  {
    id: "11320",
    name: "도봉구",
    color: "#283618",
    hotspot: "쌍문동",
    vibe: "자연친화",
    rating: 4.1,
    visitors: "1.0K",
  },
  {
    id: "11230",
    name: "동대문구",
    color: "#cdcdcd",
    hotspot: "경동시장",
    vibe: "전통시장",
    rating: 4.3,
    visitors: "1.7K",
  },
  {
    id: "11590",
    name: "동작구",
    color: "#FFB5A7",
    hotspot: "사당·노량진",
    vibe: "활력",
    rating: 4.2,
    visitors: "1.4K",
  },
  {
    id: "11440",
    name: "마포구",
    color: "#95E1D3",
    hotspot: "홍대·연남동",
    vibe: "힙한",
    rating: 4.9,
    visitors: "3.2K",
  },
  {
    id: "11410",
    name: "서대문구",
    color: "#F4A261",
    hotspot: "신촌·이화",
    vibe: "청춘",
    rating: 4.4,
    visitors: "1.9K",
  },
  {
    id: "11650",
    name: "서초구",
    color: "#FFB6B9",
    hotspot: "반포한강공원",
    vibe: "여유로운",
    rating: 4.6,
    visitors: "2.1K",
  },
  {
    id: "11200",
    name: "성동구",
    color: "#A8E6CF",
    hotspot: "성수동",
    vibe: "감성적",
    rating: 4.9,
    visitors: "3.0K",
  },
  {
    id: "11290",
    name: "성북구",
    color: "#8D99AE",
    hotspot: "북촌한옥마을",
    vibe: "고즈넉한",
    rating: 4.5,
    visitors: "2.0K",
  },
  {
    id: "11710",
    name: "송파구",
    color: "#FFDAC1",
    hotspot: "잠실·석촌호수",
    vibe: "역동적",
    rating: 4.6,
    visitors: "2.7K",
  },
  {
    id: "11470",
    name: "양천구",
    color: "#E0AFA0",
    hotspot: "목동",
    vibe: "정돈된",
    rating: 4.3,
    visitors: "1.5K",
  },
  {
    id: "11560",
    name: "영등포구",
    color: "#B4A7D6",
    hotspot: "여의도",
    vibe: "세련된",
    rating: 4.5,
    visitors: "2.4K",
  },
  {
    id: "11170",
    name: "용산구",
    color: "#FFE66D",
    hotspot: "이태원·한남동",
    vibe: "다국적",
    rating: 4.7,
    visitors: "2.5K",
  },
  {
    id: "11380",
    name: "은평구",
    color: "#90BE6D",
    hotspot: "연신내·불광동",
    vibe: "문화적",
    rating: 4.3,
    visitors: "1.6K",
  },
  {
    id: "11110",
    name: "종로구",
    color: "#4ECDC4",
    hotspot: "인사동·북촌",
    vibe: "전통적",
    rating: 4.8,
    visitors: "2.9K",
  },
  {
    id: "11140",
    name: "중구",
    color: "#F3722C",
    hotspot: "명동·남대문",
    vibe: "번화한",
    rating: 4.7,
    visitors: "3.1K",
  },
  {
    id: "11260",
    name: "중랑구",
    color: "#577590",
    hotspot: "망우리공원",
    vibe: "조용한",
    rating: 4.1,
    visitors: "1.2K",
  },
];

export const iconMap = {
  cafe: Coffee,
  restaurant: Coffee,
  shopping: ShoppingBag,
  culture: Camera,
  activity: Camera,
};
