import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import SyncUser from "@/components/etc/SyncUser";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "SeoulCourse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="ko">
        <body className={` antialiased `}>
          <Providers>
            <SignedIn>
              <SyncUser />
            </SignedIn>
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
